language: ruby
bundler_args: --without guard metrics
script: "bundle exec rake spec"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
before_script:
  - psql -c 'create database dm-mapper_test;' -U postgres
notifications:
  email:
    - piotr.solnica@gmail.com
