language: ruby
before_install: gem install bundler
bundler_args: --without guard metrics
script: "bundle exec rake spec:travis"
rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
  - ruby-head
before_script:
  - psql -c 'create database "dm-mapper_test";' -U postgres
notifications:
  irc: "irc.freenode.org#datamapper"
  email:
    - piotr.solnica@gmail.com
