language: ruby
bundler_args: --without guard metrics
script: "bundle exec rake ci:travis"
rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: rbx-18mode
before_script:
  - psql -c 'create database "dm-mapper_test";' -U postgres
notifications:
  email:
    - piotr.solnica@gmail.com
