language: ruby
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
before_script:
  - createdb rom_test --user postgres
script: "bundle exec rake spec"
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-19mode
notifications:
  irc:
    channels:
      - "irc.freenode.org#rom-rb"
    on_success: never
    on_failure: change
  email:
    recipients:
      - piotr.solnica@gmail.com
    on_success: never
    on_failure: change
matrix:
  include:
    - rvm: jruby-19mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
