---
Attribute:
  enabled: false
  exclude: []
BooleanParameter:
  enabled: true
ClassVariable:
  enabled: true
  exclude: []
ControlParameter:
  enabled: true
DataClump:
  enabled: true
  exclude: []
  max_copies: 2
  min_clump_size: 2
DuplicateMethodCall:
  enabled: false
  exclude: []
  max_calls: 1
FeatureEnvy:
  enabled: true
IrresponsibleModule:
  enabled: true
  exclude: []
LongParameterList:
  enabled: true
  max_params: 3
LongYieldList:
  enabled: true
  max_params: 2
NestedIterators:
  enabled: true
  max_allowed_nesting: 1
  ignore_iterators: []
NilCheck:
  enabled: true
RepeatedConditional:
  enabled: true
  exclude: []
  max_ifs: 1
TooManyInstanceVariables:
  enabled: true
  max_instance_variables: 3
  exclude:
    - ROM::Mapping::Definition
TooManyMethods:
  enabled: true
  exclude:
    - ROM::Environment
    - ROM::Relation
  max_methods: 10
TooManyStatements:
  enabled: true
  max_statements: 4
UncommunicativeMethodName:
  enabled: true
  exclude:
    - 'n'  # typically used to denote infinity in ROM code
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeModuleName:
  enabled: true
  exclude:
    - Axiom::Adapter::Sqlite3
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  accept: []
UncommunicativeParameterName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeVariableName:
  enabled: true
  exclude:
    - 'r' # typically used for 'relation' in blocks
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UnusedParameters:
  enabled: true
  exclude: []
UtilityFunction:
  enabled: true
  max_helper_calls: 0
